Feat: Check if item version is already preserved before bagging (Issue #102)
UAL-RE/ReBACH pull request #103
Opened 2024-06-17 20:58 UTC by HafeezOJ

**Description**

During preprocessing, this PR checks if a bag exists in AP Trust and Wasabi S3 bucket. It compares the hash of the current item version being prepared for bagging with the item's version hash in AP Trust if the item version has already been preserved. The article version will be skipped if a match is found else it's bag will be updated. All activities are logged.

See #93 

**Documentation Update**

 - [X] I have updated README.md and other relevant documentation
 - [ ] No documentation update is needed

*Implementation Notes*

This PR contains Utils.py in the figshare directory which houses utility functions. The following functions are available in this PR:
- standardize_api_result: This standardizes results from APIs. It replaces 'null' with an empty string to have a constant value for empty fields in API results.
- sorter_api_result: This recursively sorts results from APIs. The sorting ensures a consistent arrangement of fields in API results to facilitate the generation of a constant hash for the result at any time.
- get_preserved_version_hash_and_size: This connects to AP Trust to extract hash and size of an already preserved article version if one exists.
- compare_hash: This compares the hash value of the current article version in pre-processing with the hash of the article version in AP Trust.
- check_wasabi: This checks if an article version has already been preserved in Wasabi S3 bucket.

Bag checks are carried out in Article.py and Collection.py inside the figshare directory. Logging is done in app.py

2024-07-30 20:09 UTC, zoidy requested changes
Before I can continue testing, please address 

- The issues in my test results sheet.
- The comments in the code

2024-09-04 22:01 UTC, zoidy requested changes
The summary log behavior for collections is different than for articles. E.g. when a collection is already in Wasabi, a warning is output for collections but not for articles. Also the counters and text are somewhat different. For consistency, they should be the same ( minus the parts about matching obviously)

2024-09-04 23:18 UTC, HafeezOJ commented on figshare/Article.py
> +from ReBACH.figshare.Utils import calculate_payload_size
PyCharm auto-import for functions in another folder 😞

2024-09-09 15:48 UTC, HafeezOJ commented on README.md
> +	    - url - required: The AP Trust API url (identifier__starts_with filter must be included in the url)
README has been updated with actual configuration requirements for the APTrust API.

2024-09-09 15:49 UTC, HafeezOJ commented on figshare/Article.py
> +from ReBACH.figshare.Utils import calculate_payload_size
This has been corrected to standard import.

2024-09-09 15:55 UTC, HafeezOJ commented on app.py
> +                          "Total processed articles bags already in preservation storage found by Bagger: \t\t\t"
1. Storage locations in the logs have been represented as they appear in the ReBACH spec. 
2. Log info by Bagger on duplicate bag counts has been turned into a warning and only appears if an item escapes the check.
3. Counter figures have been aligned.

2024-09-09 16:00 UTC, HafeezOJ commented on figshare/Article.py
> +                             already preserved in Wasabi.", True)
All occurrences have been changed.

2024-09-09 16:05 UTC, HafeezOJ commented on app.py
> +                          True)
This logs the number of articles and the number of article versions already preserved as articles can have multiple versions. Log texts for collections have been reordered to match log text for articles.

2024-09-09 16:15 UTC, HafeezOJ reviewed
Your comments have been implemented. You can continue to review.

2024-09-11 22:44 UTC, zoidy requested changes
1. The code seems to fail on embargoed content. Please see the spreadsheet. 
2. I also further cleaned up and prettified the log outputs. The counts haven't changed, I just made them display more consistently (I think). Have a look to see if it makes sense

2024-09-12 00:44 UTC, HafeezOJ commented
1. I tried to recreate the error but embargoed items were preserved and skipped when they were already preserved. It seems you forgot to set up a curation staging directory for the embargoed item which might have caused the failure. Try to set up a curation staging directory and try again.
2. The log output is okay. I understand what the messages are saying.

2024-09-12 14:15 UTC, zoidy commented
> 1. I tried to recreate the error but embargoed items were preserved and skipped when they were already preserved. It seems you forgot to set up a curation staging directory for the embargoed item which might have caused the failure. Try to set up a curation staging directory and try again.
It can't be an issue with curation staging directory because the error occurs during the fetching stage, not the matching stage. In any case, I checked the curation folder just to be sure and indeed, the embargoed item is there. See my slack message.


> 2. The log output makes sense. I understand what the messages are saying.
Excellent!

2024-09-16 16:17 UTC, HafeezOJ commented
Sizes of skipped items have been excluded from size calculation for space check.

2024-09-16 16:19 UTC, HafeezOJ reviewed
Sizes of skipped items have been excluded from size calculation for space check.

2024-09-16 17:30 UTC, zoidy approved these changes

2024-09-16 17:32 UTC, merged